### PR TITLE
Added code to properly label elements for screen readers

### PR DESCRIPTION
**Pull request by acrawly**
Two changes:
1. Changed code to add `<label for='id'>` when the id field has been specified on a field.
2. For radio groups, wrapped them in `<fieldset>` element. 

I don't know how to do versioning so I changed the version to 1.3.1 where applicable.

### CODE REVIEW

**Comment by felixarntz** [comment]
I see the issue with the missing `<label for="">` attributes, but why do we need a `<fieldset>` on radio groups?

**Comment by acrawly** [comment]
Because under the WCAG 2.0 standards, radio buttons must be grouped together within a fieldset tag to show they are related. Technically, we must also have a `<legend>` element as well but I couldn't figure out a way to easily do this with existing code. Adding the fieldset tag has no affect on Bootstrap's styling from my reading. 

We could take it out or perhaps add an option which wraps checkboxes and radio buttons in the field set? Let me know your thoughts around this and I can change a few more things. 

UPDATE: forgot my reference, <a href="https://www.w3.org/TR/WCAG20-TECHS/H71.html">here</a>

**Comment by felixarntz** [comment]
I think you might have forgotten to add the fieldset to the checkbox group, I only see it for the radio group right now.

Anyway, I like this conditional approach with a setting. Can you add the fieldset to the checkbox group too? Then I'll merge it in and create a setting for it.

**Comment by acrawly** [comment]
Right, I forgot. I've added the fieldsets for the options, let me know what option you end up making it! :) Thanks for your help.

**Pull request merged**
